# site settings
title: iTron
subtitle:
email: itron2025@gmail.com
description: 來自交大機械系的學生團隊，專注於機械設計與控制，用創意和行動把天馬行空變成真實機器！
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://NYCU-iTron.github.io"
author:
address:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/NYCU-iTron
  Instagram: https://www.instagram.com/itron_nycu/
  Facebook: https://www.facebook.com/NCTU.iTron

# build settings
markdown: kramdown

sass:
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

# Fix the warning: " GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data."
github: [metadata]
